pub mod api;
pub mod config;
pub mod db;
pub mod errors;
pub mod services;
pub mod state;

pub use config::Config;
pub use db::DbPool;
pub use errors::{AppError, Result};
pub use state::{AppState, AppStateBuilder};

use axum::{
    routing::{get, post, put, delete},
    Router,
    Extension,
};
use std::sync::Arc;

pub fn routes(app_state: Arc<AppState>) -> Router {
    Router::new()
        .route("/health", get(|| async { "OK" }))
        
        .route("/api/v1/auth/login", post(crate::api::handlers::auth::login_handler))
        .route("/api/v1/auth/register", post(crate::api::handlers::auth::register_handler))
        .route("/api/v1/auth/users", get(crate::api::handlers::auth::get_users_handler))
        .route("/api/v1/auth/users", post(crate::api::handlers::auth::create_user_handler))
        .route("/api/v1/auth/users/{id}", get(crate::api::handlers::auth::get_user_info_handler))
        .route("/api/v1/auth/users/{id}", put(crate::api::handlers::auth::update_user_handler))
        .route("/api/v1/auth/users/{id}", delete(crate::api::handlers::auth::delete_user_handler))
        .route("/api/v1/auth/users/{id}/status", put(crate::api::handlers::auth::update_user_status_handler))
        
        // 工作台/Dashboard API
        .route("/api/v1/dashboard/stats", get(crate::api::handlers::dashboard::get_dashboard_stats_handler))
        .route("/api/v1/dashboard/production-trend", get(crate::api::handlers::dashboard::get_production_trend_handler))
        .route("/api/v1/dashboard/department-distribution", get(crate::api::handlers::dashboard::get_department_distribution_handler))
        .route("/api/v1/dashboard/attendance-summary", get(crate::api::handlers::dashboard::get_attendance_summary_handler))
        .route("/api/v1/dashboard/approval-stats", get(crate::api::handlers::dashboard::get_approval_stats_handler))
        .route("/api/v1/dashboard/leave-distribution", get(crate::api::handlers::dashboard::get_leave_type_distribution_handler))
        
        .route("/api/v1/auth/users/{id}/approve", post(crate::api::handlers::auth::approve_user_handler))
        .route("/api/v1/auth/users/{id}/password", put(crate::api::handlers::auth::change_password_handler))
        .route("/api/v1/auth/users/pending", get(crate::api::handlers::auth::get_pending_users_handler))
        
        .route("/api/v1/users/{id}/info", get(crate::api::handlers::auth::get_user_info_handler))
        
        .route("/api/v1/departments", get(crate::api::handlers::organization::get_departments_handler))
        .route("/api/v1/departments", post(crate::api::handlers::organization::create_department_handler))
        .route("/api/v1/departments/{id}", get(crate::api::handlers::organization::get_department_handler))
        .route("/api/v1/departments/{id}", put(crate::api::handlers::organization::update_department_handler))
        .route("/api/v1/departments/{id}", delete(crate::api::handlers::organization::delete_department_handler))
        .route("/api/v1/departments/{id}/status", put(crate::api::handlers::organization::update_department_status_handler))
        .route("/api/v1/departments/{parent_id}/children", get(crate::api::handlers::organization::get_department_children_handler))
        
        .route("/api/v1/organization/positions", get(crate::api::handlers::organization::get_positions_handler))
        .route("/api/v1/organization/positions", post(crate::api::handlers::organization::create_position_handler))
        .route("/api/v1/organization/positions/{id}", get(crate::api::handlers::organization::get_position_handler))
        .route("/api/v1/organization/positions/{id}", put(crate::api::handlers::organization::update_position_handler))
        .route("/api/v1/organization/positions/{id}", delete(crate::api::handlers::organization::delete_position_handler))
        .route("/api/v1/organization/positions/department/{department_id}", get(crate::api::handlers::organization::get_positions_by_department_handler))
        
        .route("/api/v1/organization/position-levels", get(crate::api::handlers::organization::get_position_levels_handler))
        .route("/api/v1/organization/position-levels", post(crate::api::handlers::organization::create_position_level_handler))
        .route("/api/v1/organization/position-levels/{id}", put(crate::api::handlers::organization::update_position_level_handler))
        .route("/api/v1/organization/position-levels/{id}", delete(crate::api::handlers::organization::delete_position_level_handler))
        
        .route("/api/v1/organization/approval-rules", get(crate::api::handlers::organization::get_approval_rules_handler))
        .route("/api/v1/organization/approval-rules", post(crate::api::handlers::organization::create_approval_rule_handler))
        .route("/api/v1/organization/approval-rules/{id}", put(crate::api::handlers::organization::update_approval_rule_handler))
        .route("/api/v1/organization/approval-rules/{id}", delete(crate::api::handlers::organization::delete_approval_rule_handler))
        
        .route("/api/v1/hr/employees", get(crate::api::handlers::hr::get_employees_handler))
        .route("/api/v1/hr/employees", post(crate::api::handlers::hr::create_employee_handler))
        .route("/api/v1/hr/employees/{id}", get(crate::api::handlers::hr::get_employee_handler))
        .route("/api/v1/hr/employees/{id}", put(crate::api::handlers::hr::update_employee_handler))
        .route("/api/v1/hr/employees/{id}", delete(crate::api::handlers::hr::delete_employee_handler))
        .route("/api/v1/hr/employees/convert", post(crate::api::handlers::hr::convert_to_employee_handler))
        
        .route("/api/v1/hr/positions", get(crate::api::handlers::organization::get_positions_handler))
        .route("/api/v1/hr/positions", post(crate::api::handlers::organization::create_position_handler))
        .route("/api/v1/hr/positions/{id}", put(crate::api::handlers::organization::update_position_handler))
        .route("/api/v1/hr/positions/{id}", delete(crate::api::handlers::organization::delete_position_handler))
        
        .route("/api/v1/hr/attendance/today", get(crate::api::handlers::hr::get_attendance_today_handler))
        .route("/api/v1/hr/attendance/records", get(crate::api::handlers::hr::get_attendance_records_handler))
        .route("/api/v1/hr/attendance/statistics", get(crate::api::handlers::hr::get_attendance_stats_handler))
        .route("/api/v1/hr/attendance/month", get(crate::api::handlers::hr::get_attendance_month_handler))
        .route("/api/v1/hr/attendance/check-in", post(crate::api::handlers::hr::check_in_handler))
        .route("/api/v1/hr/attendance/check-out", post(crate::api::handlers::hr::check_out_handler))
        
        .route("/api/v1/hr/leave", get(crate::api::handlers::hr::get_leave_requests_handler))
        .route("/api/v1/hr/leave", post(crate::api::handlers::hr::create_leave_request_handler))
        .route("/api/v1/hr/leave/{id}", get(crate::api::handlers::hr::get_leave_request_handler))
        .route("/api/v1/hr/leave/{id}", put(crate::api::handlers::hr::update_leave_request_handler))
        .route("/api/v1/hr/leave/{id}", delete(crate::api::handlers::hr::delete_leave_request_handler))
        .route("/api/v1/hr/leave/{id}/approve", post(crate::api::handlers::hr::approve_leave_request_handler))
        
        .route("/api/v1/cms/categories", get(crate::api::handlers::cms::get_categories_handler))
        .route("/api/v1/cms/categories", post(crate::api::handlers::cms::create_category_handler))
        .route("/api/v1/cms/articles", get(crate::api::handlers::cms::get_articles_handler))
        .route("/api/v1/cms/articles", post(crate::api::handlers::cms::create_article_handler))
        .route("/api/v1/cms/articles/{id}", get(crate::api::handlers::cms::get_article_handler))
        .route("/api/v1/cms/articles/{id}", put(crate::api::handlers::cms::update_article_handler))
        .route("/api/v1/cms/articles/{id}/review", post(crate::api::handlers::cms::submit_article_for_review_handler))
        .route("/api/v1/cms/articles/{id}/reviews", post(crate::api::handlers::cms::review_article_handler))
        .route("/api/v1/cms/articles/{id}/reviews/list", get(crate::api::handlers::cms::get_article_reviews_handler))
        .route("/api/v1/cms/articles/pending-review", get(crate::api::handlers::cms::get_pending_review_articles_handler))
        .route("/api/v1/cms/articles/reviewing", get(crate::api::handlers::cms::get_reviewing_articles_handler))
        .route("/api/v1/cms/articles/reviewed", get(crate::api::handlers::cms::get_reviewed_articles_handler))
        .route("/api/v1/cms/articles/{id}/assign-reviewer", post(crate::api::handlers::cms::assign_reviewer_handler))
        .route("/api/v1/cms/articles/{id}/publish", post(crate::api::handlers::cms::publish_article_handler))
        .route("/api/v1/cms/articles/{id}/archive", post(crate::api::handlers::cms::archive_article_handler))
        .route("/api/v1/cms/articles/{id}/restore", post(crate::api::handlers::cms::restore_article_handler))
        .route("/api/v1/cms/review/stats", get(crate::api::handlers::cms::get_review_stats_handler))
        .route("/api/v1/cms/review/assignments", get(crate::api::handlers::cms::get_review_assignments_handler))
        .route("/api/v1/cms/public/articles", get(crate::api::handlers::cms::get_public_articles_handler))
        
        .route("/api/v1/workflows", get(crate::api::handlers::workflow::get_workflows_handler))
        .route("/api/v1/workflows", post(crate::api::handlers::workflow::create_workflow_handler))
        .route("/api/v1/workflows/{id}", put(crate::api::handlers::workflow::update_workflow_handler))
        .route("/api/v1/workflows/{id}", delete(crate::api::handlers::workflow::delete_workflow_handler))
        .route("/api/v1/workflows/{id}/nodes", get(crate::api::handlers::workflow::get_workflow_nodes_handler))
        .route("/api/v1/workflows/nodes", post(crate::api::handlers::workflow::create_workflow_node_handler))
        .route("/api/v1/workflows/nodes/{id}", put(crate::api::handlers::workflow::update_workflow_node_handler))
        .route("/api/v1/workflows/nodes/{id}", delete(crate::api::handlers::workflow::delete_workflow_node_handler))
        
        .route("/api/v1/workflow/tasks/my-tasks", get(crate::api::handlers::workflow::get_my_tasks_handler))
        .route("/api/v1/workflow/tasks/my-initiated", get(crate::api::handlers::workflow::get_my_initiated_handler))
        .route("/api/v1/workflow/tasks/my", get(crate::api::handlers::workflow::get_my_tasks_handler))
        .route("/api/v1/workflow/tasks/initiated", get(crate::api::handlers::workflow::get_my_initiated_handler))
        .route("/api/v1/workflow/tasks/{id}", get(crate::api::handlers::workflow::get_task_detail_handler))
        .route("/api/v1/workflow/tasks/{id}/records", get(crate::api::handlers::workflow::get_task_records_handler))
        .route("/api/v1/workflow/tasks/{id}/approve", post(crate::api::handlers::workflow::approve_task_handler))
        .route("/api/v1/workflow/tasks", post(crate::api::handlers::workflow::create_approval_task_handler))
        .route("/api/v1/workflow/history", get(crate::api::handlers::workflow::get_approval_history_handler))
        .route("/api/v1/workflow/history/my-initiated", get(crate::api::handlers::workflow::get_my_initiated_history_handler))
        .route("/api/v1/workflow/users", get(crate::api::handlers::workflow::get_all_users_handler))
        .route("/api/v1/workflow/init-default", post(crate::api::handlers::workflow::init_default_workflows_handler))
        
        .route("/api/v1/schedule/events", get(crate::api::handlers::schedule::get_schedule_events_handler))
        .route("/api/v1/schedule/events/{id}", get(crate::api::handlers::schedule::get_schedule_event_handler))
        .route("/api/v1/schedule/events", post(crate::api::handlers::schedule::create_schedule_event_handler))
        .route("/api/v1/schedule/events/{id}", put(crate::api::handlers::schedule::update_schedule_event_handler))
        .route("/api/v1/schedule/events/{id}", delete(crate::api::handlers::schedule::delete_schedule_event_handler))
        
        .route("/api/v1/website/settings", get(crate::api::handlers::website::get_website_settings_handler))
        .route("/api/v1/website/settings", put(crate::api::handlers::website::update_website_settings_handler))
        .route("/api/v1/website/deployments", get(crate::api::handlers::website::get_website_deployments_handler))
        .route("/api/v1/website/deploy", post(crate::api::handlers::website::deploy_website_handler))
        .route("/api/v1/website/generate", post(crate::api::handlers::website::generate_website_handler))
        .route("/api/v1/website/preview", post(crate::api::handlers::website::preview_website_handler))
        
        .route("/api/v1/ai/status", get(crate::api::handlers::ai::get_ai_status_handler))
        .route("/api/v1/ai/generate-image", post(crate::api::handlers::ai::generate_image_handler))
        
        .route("/api/v1/help/categories", get(crate::api::handlers::help::get_categories_handler))
        .route("/api/v1/help/categories", post(crate::api::handlers::help::create_category_handler))
        .route("/api/v1/help/categories/{id}", get(crate::api::handlers::help::get_category_handler))
        .route("/api/v1/help/categories/{id}", put(crate::api::handlers::help::update_category_handler))
        .route("/api/v1/help/categories/{id}", delete(crate::api::handlers::help::delete_category_handler))
        .route("/api/v1/help/articles", get(crate::api::handlers::help::get_articles_handler))
        .route("/api/v1/help/articles", post(crate::api::handlers::help::create_article_handler))
        .route("/api/v1/help/articles/{id}", get(crate::api::handlers::help::get_article_handler))
        .route("/api/v1/help/articles/{id}", put(crate::api::handlers::help::update_article_handler))
        .route("/api/v1/help/articles/{id}", delete(crate::api::handlers::help::delete_article_handler))
        .route("/api/v1/help/search", get(crate::api::handlers::help::search_help_handler))
        .route("/api/v1/help/init-defaults", post(crate::api::handlers::help::init_default_help_handler))
        
        .route("/api/v1/document-ai/optimize", post(crate::api::handlers::ai::optimize_document_handler))
        
        .route("/api/v1/production-docs/categories", get(crate::api::handlers::production_docs::get_document_categories_handler))
        .route("/api/v1/production-docs/categories", post(crate::api::handlers::production_docs::create_document_category_handler))
        .route("/api/v1/production-docs/categories/{code}", get(crate::api::handlers::production_docs::get_document_category_by_code_handler))
        .route("/api/v1/production-docs/documents", get(crate::api::handlers::production_docs::get_production_documents_handler))
        .route("/api/v1/production-docs/documents", post(crate::api::handlers::production_docs::create_production_document_handler))
        .route("/api/v1/production-docs/documents/{id}", get(crate::api::handlers::production_docs::get_production_document_handler))
        .route("/api/v1/production-docs/documents/{id}", put(crate::api::handlers::production_docs::update_production_document_handler))
        .route("/api/v1/production-docs/documents/{id}", delete(crate::api::handlers::production_docs::delete_production_document_handler))
        .route("/api/v1/production-docs/documents/{id}/review", post(crate::api::handlers::production_docs::submit_review_document_handler))
        .route("/api/v1/production-docs/documents/{id}/review/approve", post(crate::api::handlers::production_docs::review_document_handler))
        .route("/api/v1/production-docs/documents/for-review", get(crate::api::handlers::production_docs::get_for_review_documents_handler))
        
        .route("/api/v1/materials", get(crate::api::handlers::material_library::list_materials_handler))
        .route("/api/v1/materials", post(crate::api::handlers::material_library::create_material_handler))
        .route("/api/v1/materials/{id}", get(crate::api::handlers::material_library::get_material_handler))
        .route("/api/v1/materials/{id}", put(crate::api::handlers::material_library::update_material_handler))
        .route("/api/v1/materials/{id}", delete(crate::api::handlers::material_library::delete_material_handler))
        .route("/api/v1/materials/crawl", post(crate::api::handlers::material_library::crawl_url_handler))
        
        .route("/api/v1/erp/products", get(crate::api::handlers::erp_inventory::get_products_handler))
        .route("/api/v1/erp/products", post(crate::api::handlers::erp_inventory::create_product_handler))
        .route("/api/v1/erp/products/{id}", get(crate::api::handlers::erp_inventory::get_product_handler))
        .route("/api/v1/erp/warehouses", get(crate::api::handlers::erp_inventory::get_warehouses_handler))
        .route("/api/v1/erp/warehouses", post(crate::api::handlers::erp_inventory::create_warehouse_handler))
        .route("/api/v1/erp/inventory", get(crate::api::handlers::erp_inventory::get_inventory_handler))
        .route("/api/v1/erp/inventory/logs", get(crate::api::handlers::erp_inventory::get_inventory_logs_handler))
        
        .route("/api/v1/erp/purchase/suppliers", get(crate::api::handlers::erp_purchase::get_suppliers_handler))
        .route("/api/v1/erp/purchase/suppliers", post(crate::api::handlers::erp_purchase::create_supplier_handler))
        .route("/api/v1/erp/purchase/suppliers/{id}", get(crate::api::handlers::erp_purchase::get_supplier_handler))
        .route("/api/v1/erp/purchase/orders", get(crate::api::handlers::erp_purchase::get_purchase_orders_handler))
        .route("/api/v1/erp/purchase/orders", post(crate::api::handlers::erp_purchase::create_purchase_order_handler))
        .route("/api/v1/erp/purchase/receipts", get(crate::api::handlers::erp_purchase::get_purchase_receipts_handler))
        
        .route("/api/v1/erp/sales/customers", get(crate::api::handlers::erp_sales::get_customers_handler))
        .route("/api/v1/erp/sales/customers", post(crate::api::handlers::erp_sales::create_customer_handler))
        .route("/api/v1/erp/sales/customers/{id}", get(crate::api::handlers::erp_sales::get_customer_handler))
        .route("/api/v1/erp/sales/orders", get(crate::api::handlers::erp_sales::get_sales_orders_handler))
        .route("/api/v1/erp/sales/orders", post(crate::api::handlers::erp_sales::create_sales_order_handler))
        .route("/api/v1/erp/sales/deliveries", get(crate::api::handlers::erp_sales::get_sales_deliveries_handler))
        
        .route("/api/v1/field/records", get(crate::api::handlers::field::get_all_records))
        .route("/api/v1/field/records", post(crate::api::handlers::field::create_record))
        .route("/api/v1/field/records/{id}", get(crate::api::handlers::field::get_record))
        .route("/api/v1/field/records/{id}", put(crate::api::handlers::field::update_record))
        .route("/api/v1/field/records/{id}", delete(crate::api::handlers::field::delete_record))
        .route("/api/v1/field/records/{id}/photos", post(crate::api::handlers::field::upload_photo))
        .route("/api/v1/field/records/{record_id}/photos/{photo_id}", delete(crate::api::handlers::field::delete_photo))
        .route("/api/v1/field/records/{id}/audio", post(crate::api::handlers::field::upload_audio))
        .route("/api/v1/field/records/{record_id}/audio/{audio_id}", delete(crate::api::handlers::field::delete_audio))
        .route("/api/v1/field/my-records", get(crate::api::handlers::field::get_user_records))
        
        .route("/api/v1/gis/customers", get(crate::api::handlers::gis::get_customers_handler))
        .route("/api/v1/gis/customers", post(crate::api::handlers::gis::create_customer_handler))
        .route("/api/v1/gis/customers/{id}", get(crate::api::handlers::gis::get_customer_handler))
        .route("/api/v1/gis/customers/{id}", put(crate::api::handlers::gis::update_customer_handler))
        .route("/api/v1/gis/customers/{id}", delete(crate::api::handlers::gis::delete_customer_handler))
        
        .route("/api/v1/gis/projects", get(crate::api::handlers::gis::get_projects_handler))
        .route("/api/v1/gis/projects", post(crate::api::handlers::gis::create_project_handler))
        .route("/api/v1/gis/projects/{id}", get(crate::api::handlers::gis::get_project_handler))
        .route("/api/v1/gis/projects/{id}", put(crate::api::handlers::gis::update_project_handler))
        .route("/api/v1/gis/projects/{id}", delete(crate::api::handlers::gis::delete_project_handler))
        
        .route("/api/v1/gis/warehouses", get(crate::api::handlers::gis::get_warehouses_handler))
        .route("/api/v1/gis/warehouses", post(crate::api::handlers::gis::create_warehouse_handler))
        .route("/api/v1/gis/warehouses/{id}", get(crate::api::handlers::gis::get_warehouse_handler))
        .route("/api/v1/gis/warehouses/{id}", put(crate::api::handlers::gis::update_warehouse_handler))
        .route("/api/v1/gis/warehouses/{id}", delete(crate::api::handlers::gis::delete_warehouse_handler))
        
        .route("/api/v1/gis/personnel", get(crate::api::handlers::gis::get_personnel_handler))
        .route("/api/v1/gis/personnel", post(crate::api::handlers::gis::create_personnel_handler))
        .route("/api/v1/gis/personnel/{id}", get(crate::api::handlers::gis::get_personnel_by_id_handler))
        .route("/api/v1/gis/personnel/{id}", put(crate::api::handlers::gis::update_personnel_handler))
        .route("/api/v1/gis/personnel/{id}", delete(crate::api::handlers::gis::delete_personnel_handler))
        .route("/api/v1/gis/personnel/{id}/location", put(crate::api::handlers::gis::update_personnel_location_handler))
        
        .route("/api/v1/gis/markers", get(crate::api::handlers::gis::get_markers_handler))
        .route("/api/v1/gis/markers", post(crate::api::handlers::gis::create_marker_handler))
        .route("/api/v1/gis/markers/{id}", get(crate::api::handlers::gis::get_marker_handler))
        .route("/api/v1/gis/markers/{id}", put(crate::api::handlers::gis::update_marker_handler))
        .route("/api/v1/gis/markers/{id}", delete(crate::api::handlers::gis::delete_marker_handler))
        .route("/api/v1/gis/markers/nearby", get(crate::api::handlers::gis::search_nearby_markers_handler))
        .route("/api/v1/gis/markers/types", get(crate::api::handlers::gis::get_marker_types_handler))
        .route("/api/v1/gis/markers/layers", get(crate::api::handlers::gis::get_layers_handler))
        
        .route("/api/v1/projects", get(crate::api::handlers::project::search_projects_handler))
        .route("/api/v1/projects", post(crate::api::handlers::project::create_project_handler))
        .route("/api/v1/projects/{id}", get(crate::api::handlers::project::get_project_handler))
        .route("/api/v1/projects/{id}", put(crate::api::handlers::project::update_project_handler))
        .route("/api/v1/projects/{id}", delete(crate::api::handlers::project::delete_project_handler))
        .route("/api/v1/projects/stats", get(crate::api::handlers::project::get_project_stats_handler))
        
        .route("/api/v1/projects/{project_id}/phases", post(crate::api::handlers::project::create_phase_handler))
        .route("/api/v1/projects/{project_id}/phases", get(crate::api::handlers::project::get_phases_handler))
        .route("/api/v1/phases/{id}", put(crate::api::handlers::project::update_phase_handler))
        .route("/api/v1/phases/{id}", delete(crate::api::handlers::project::delete_phase_handler))
        
        .route("/api/v1/projects/{project_id}/tasks", post(crate::api::handlers::project::create_task_handler))
        .route("/api/v1/projects/{project_id}/tasks", get(crate::api::handlers::project::get_tasks_handler))
        .route("/api/v1/tasks/{id}", get(crate::api::handlers::project::get_task_handler))
        .route("/api/v1/tasks/{id}", put(crate::api::handlers::project::update_task_handler))
        .route("/api/v1/tasks/{id}", delete(crate::api::handlers::project::delete_task_handler))
        
        .route("/api/v1/projects/{project_id}/team", post(crate::api::handlers::project::add_team_member_handler))
        .route("/api/v1/projects/{project_id}/team", get(crate::api::handlers::project::get_team_handler))
        .route("/api/v1/team/{id}", put(crate::api::handlers::project::update_team_member_handler))
        .route("/api/v1/team/{id}", delete(crate::api::handlers::project::remove_team_member_handler))
        
        .route("/api/v1/projects/{project_id}/milestones", post(crate::api::handlers::project::create_milestone_handler))
        .route("/api/v1/projects/{project_id}/milestones", get(crate::api::handlers::project::get_milestones_handler))
        .route("/api/v1/milestones/{id}", put(crate::api::handlers::project::update_milestone_handler))
        .route("/api/v1/milestones/{id}", delete(crate::api::handlers::project::delete_milestone_handler))
        
        .route("/api/v1/projects/{project_id}/risks", post(crate::api::handlers::project::create_risk_handler))
        .route("/api/v1/projects/{project_id}/risks", get(crate::api::handlers::project::get_risks_handler))
        .route("/api/v1/risks/{id}", put(crate::api::handlers::project::update_risk_handler))
        .route("/api/v1/risks/{id}", delete(crate::api::handlers::project::delete_risk_handler))
        
        .route("/api/v1/projects/{project_id}/issues", post(crate::api::handlers::project::create_issue_handler))
        .route("/api/v1/projects/{project_id}/issues", get(crate::api::handlers::project::get_issues_handler))
        .route("/api/v1/issues/{id}", put(crate::api::handlers::project::update_issue_handler))
        .route("/api/v1/issues/{id}", delete(crate::api::handlers::project::delete_issue_handler))
        
        .route("/api/v1/projects/{project_id}/costs", post(crate::api::handlers::project::add_cost_handler))
        .route("/api/v1/projects/{project_id}/costs", get(crate::api::handlers::project::get_costs_handler))
        .route("/api/v1/costs/{id}", delete(crate::api::handlers::project::delete_cost_handler))
        
        .route("/api/v1/contracts/templates", get(crate::api::handlers::contract::get_contract_templates))
        .route("/api/v1/contracts/templates", post(crate::api::handlers::contract::create_contract_template))
        .route("/api/v1/contracts/templates/{id}", get(crate::api::handlers::contract::get_contract_template))
        .route("/api/v1/contracts/templates/{id}", put(crate::api::handlers::contract::update_contract_template))
        .route("/api/v1/contracts/templates/{id}", delete(crate::api::handlers::contract::delete_contract_template))
        
        .route("/api/v1/contracts", get(crate::api::handlers::contract::get_contracts))
        .route("/api/v1/contracts", post(crate::api::handlers::contract::create_contract))
        .route("/api/v1/contracts/{id}", get(crate::api::handlers::contract::get_contract))
        .route("/api/v1/contracts/{id}", put(crate::api::handlers::contract::update_contract))
        .route("/api/v1/contracts/{id}", delete(crate::api::handlers::contract::delete_contract))
        
        .route("/api/v1/roles", get(crate::api::handlers::role::get_roles_handler))
        .route("/api/v1/roles", post(crate::api::handlers::role::create_role_handler))
        .route("/api/v1/roles/{id}", get(crate::api::handlers::role::get_role_handler))
        .route("/api/v1/roles/{id}", put(crate::api::handlers::role::update_role_handler))
        .route("/api/v1/roles/{id}", delete(crate::api::handlers::role::delete_role_handler))
        .route("/api/v1/roles/{id}/permissions", get(crate::api::handlers::role::get_role_permissions_handler))
        .route("/api/v1/roles/{id}/permissions", put(crate::api::handlers::role::assign_permissions_handler))
        .route("/api/v1/roles/active", get(crate::api::handlers::role::get_active_roles_handler))
        .route("/api/v1/permissions", get(crate::api::handlers::role::get_all_permissions_handler))
        
        .route("/api/v1/users/all", get(crate::api::handlers::auth::get_all_users_handler))
        
        .route("/api/v1/workflows/init-defaults", post(crate::api::handlers::workflow::init_default_workflows_handler))
        
        .route("/api/v1/dicts/categories", get(crate::api::handlers::dict::get_dict_categories_handler))
        .route("/api/v1/dicts/categories", post(crate::api::handlers::dict::create_dict_category_handler))
        .route("/api/v1/dicts/categories/{id}", get(crate::api::handlers::dict::get_dict_type_handler))
        .route("/api/v1/dicts/types/{id}", get(crate::api::handlers::dict::get_dict_type_handler))
        .route("/api/v1/dicts/categories/{id}", put(crate::api::handlers::dict::update_dict_type_handler))
        .route("/api/v1/dicts/categories/{id}", delete(crate::api::handlers::dict::delete_dict_type_handler))
        .route("/api/v1/dicts/categories/{id}/items", get(crate::api::handlers::dict::get_dict_type_with_items_handler))
        .route("/api/v1/dicts/categories/{id}/with-items", get(crate::api::handlers::dict::get_dict_type_with_items_handler))
        .route("/api/v1/dicts/categories/code/{code}/items", get(crate::api::handlers::dict::get_dict_items_by_category_handler))
        .route("/api/v1/dicts/items", get(crate::api::handlers::dict::get_dict_items_handler))
        .route("/api/v1/dicts/items", post(crate::api::handlers::dict::create_dict_item_handler))
        .route("/api/v1/dicts/items/{id}", put(crate::api::handlers::dict::update_dict_item_handler))
        .route("/api/v1/dicts/items/{id}", delete(crate::api::handlers::dict::delete_dict_item_handler))
        .route("/api/v1/dicts/by-code/{code}", get(crate::api::handlers::dict::get_dict_items_by_category_handler))
        .route("/api/v1/dicts/all", get(crate::api::handlers::dict::get_all_dicts_handler))
        .route("/api/v1/dicts/init-defaults", post(crate::api::handlers::dict::init_default_dicts_handler))
        
        .route("/api/v1/approval-comment/generate", post(crate::api::handlers::approval_comment::generate_comment_handler))
        .route("/api/v1/approval-comment/optimize", post(crate::api::handlers::approval_comment::optimize_comment_handler))
        
        .route("/api/v1/ai/translate", post(crate::api::handlers::english_ai::translate_handler))
        .route("/api/v1/english-ai/generate-description", post(crate::api::handlers::english_ai::generate_description_handler))
        .route("/api/v1/english-ai/suggest-naming", post(crate::api::handlers::english_ai::suggest_naming_handler))
        .route("/api/v1/english-ai/terminology", get(crate::api::handlers::english_ai::get_terminology_handler))
        
        // 统一模板管理
        .route("/api/v1/templates", get(crate::api::handlers::templates::get_templates_handler))
        .route("/api/v1/templates", post(crate::api::handlers::templates::create_template_handler))
        .route("/api/v1/templates/{id}", get(crate::api::handlers::templates::get_template_handler))
        .route("/api/v1/templates/{id}", put(crate::api::handlers::templates::update_template_handler))
        .route("/api/v1/templates/{id}", delete(crate::api::handlers::templates::delete_template_handler))
        .route("/api/v1/templates/code/{code}", get(crate::api::handlers::templates::get_template_by_code_handler))
        .route("/api/v1/templates/categories", get(crate::api::handlers::templates::get_template_categories_handler))
        .route("/api/v1/templates/usage", post(crate::api::handlers::templates::record_template_usage_handler))
        .route("/api/v1/templates/init-defaults", post(crate::api::handlers::templates::init_default_templates_handler))
        .route("/api/v1/templates/favorites", get(crate::api::handlers::templates::get_favorites_handler))
        .route("/api/v1/templates/favorites/toggle", post(crate::api::handlers::templates::toggle_favorite_handler))
        .route("/api/v1/templates/{id}/versions", get(crate::api::handlers::templates::get_versions_handler))
        .route("/api/v1/templates/{id}/versions", post(crate::api::handlers::templates::create_version_handler))
        .route("/api/v1/templates/{id}/versions/{version_number}", get(crate::api::handlers::templates::get_version_handler))
        .route("/api/v1/templates/{id}/versions/{version_number}/rollback", post(crate::api::handlers::templates::rollback_version_handler))
        .route("/api/v1/templates/{id}/versions/{version_number}", delete(crate::api::handlers::templates::delete_version_handler))
        .route("/api/v1/templates/{id}/permissions", get(crate::api::handlers::templates::get_permissions_handler))
        .route("/api/v1/templates/{id}/permissions", post(crate::api::handlers::templates::add_permission_handler))
        .route("/api/v1/templates/permissions/{id}", delete(crate::api::handlers::templates::remove_permission_handler))
        .route("/api/v1/templates/{id}/check-access", post(crate::api::handlers::templates::check_access_handler))
        
        .layer(Extension(app_state.db.clone()))
        .with_state(app_state)
}